### ISSUE TITLE
Documentation todo list

### ISSUE THREAD

**Issue by MartinaeyNL** [MartinaeyNL/toolboard-app#12]
Here is a list of topics that might be nice to mention / discuss for later use:

- [ ] Basic setup of the Repo
- [ ] Usage of Wails within the project
- [ ] Go structs and their TypeScript generation
